### ISSUE TITLE
Jämförelse emot pris

### ISSUE THREAD

**Issue by turbonezze** [dhogborg/off-peak#13]
Först och främst, grymt bra sida, har suttit och jämfört i excel hela tiden. Tyckte bara mig inte få lika bra siffror i mina Excelfiler som jag fick på offpeak.se. Jämförpriset jag får här och det som rapporteras av Greenly / Tibber mfl stämmer inte. Jag vet inte riktigt varför.

Exempelvis den 27/3 i SE3 står det 0,62 på offgrid men på nordpool står det 57,1 kr.

**Comment by dhogborg** [comment]
Du har förmodligen jämfört snittpris (jämt snitt över alla timmar) med volymvägt snittpris. Vilken volym varje timme vägs med räknas ut från den avräkningsprofil som SVK publicerar för ditt område varje dygn.

**Comment by turbonezze** [comment]
Tack du verkar ha helt rätt, hade ingen aning om att elen prissattes så.
Lägger den här informationen här ifall det är någon mer som undrar samma sak:

Vad är volymvägning av elpris?
De flesta elhandelsföretag använder sig idag av ett volymvägt elpris och inte ett traditionellt rörligt elpris (där börsprisets månadsmedelvärde plus ett påslag för olika kostnader fakturerades). Det volymvägda elpriset innebär enkelt uttryckt att kunden betalar för elhandelsföretagets inköpspris på så sätt att elprisets timpriser på börsen och företagets kunders gemensamma elförbrukning per timme utgör underlaget för beräkningen av företagets rörliga elpris per månad. 

Det rörliga inköpspriset av el är då oftast ett viktat medelvärde av företagets inköpta energivolym för kundernas användningsprofil per timme, multiplicerat med Nord Pools timvisa spotpris för det elområde där din anläggning finns. Utöver det viktade medelvärdet tillkommer även fasta avgifter till Svenska kraftnät och Nord Pool. 

Observera att om du inte har ett timprisavtal betalar du som om du förbrukat enligt kundkollektivets förbrukningsprofil.

Det volymvägda elpriset beräknas utifrån en mängd olika faktorer och det är svårt för konsumenter att kontrollera eller beräkna det fakturerade priset. Som konsument kan man utgå från börsprisets månadsmedelvärde för [bostadens elprisområde](https://www.energimarknadsbyran.se/el/elmarknaden/elomraden/vilket-elomrade-tillhor-du/) för att få en uppfattning om elprisets utveckling.
