### ISSUE TITLE
Documentation for client.env variables

### ISSUE THREAD

**Issue by khromov** [dhogborg/off-peak#15]
I'm trying to run this project locally via `docker-compose.yml` but it complains about a missing `client.env` file. However there is not documentation for this file.

Would it be possible to create a `client.env.sample` file with the variables that need to be provided, or is is simply [these ones](https://github.com/dhogborg/off-peak/blob/master/server/main.go#L24-L32)? (And if so, is Firebase a hard requirement to run this project?)

**Comment by dhogborg** [comment]
Correct, here is the env spec: https://github.com/dhogborg/off-peak/blob/master/client.example.env

You can youse your own firebase credentials but the functionality is optional. Set dummy values if you are not developing or testing snapshot functionality.

The Tibber OAuth part requires approval from Tibber to use their SSO. This is not feasible for development work. During development, you can use a personal token from https://developer.tibber.com/settings/access-token , store it under localStorage as `access_token` and set the `expires` key to a value far in the future.
