### ISSUE TITLE
Lägga till procentuell vinst/förlust till att använda timavräkning.

### ISSUE THREAD

**Issue by nhogblom** [dhogborg/off-peak#17]
Hej,
Skulle ni inte kunna lägga till så att den visar procentuell vinst/förlust på dashboarden?
Finns ju en ledig plats bredvid Sparat som skulle passa utmärkt :)

**Comment by dhogborg** [comment]
Tack för idén, den är nu implementerad.

<img width="377" alt="Screenshot 2022-09-01 at 13 46 53" src="https://user-images.githubusercontent.com/776774/187906548-caa78d1f-874f-4f81-84df-bea6152f64c5.png">

Det hamnade tillsammans med besparingen
