### ISSUE TITLE
Värden visas men är alltid 0

### ISSUE THREAD

**Issue by oskarannas** [dhogborg/off-peak#18]
Jag får inte upp några värden under "Grafer". Se bild nedan:
![offpeak](https://user-images.githubusercontent.com/5412178/187378003-c55446ae-1912-4440-b1fe-690fae7a86c3.png)

Jag kan se i debuggern att tre anrop görs som får 200-svar:
https://api.tibber.com/v1-beta/gql (consumption)
https://api.tibber.com/v1-beta/gql (currentSubscription)
https://offpeak.se/api/v1/svkprofile?periodFrom=2022-07-29&periodTo=2022-08-30&networkAreaIdString=GTL

Datan som returneras ser ok ut, iaf utifrån vad jag kan se.

Inga fel i consolen.

Har endast haft Tibber i några dagar, kan det orsaka detta?

**Comment by dhogborg** [comment]
Ser att mätningen baseras på senaste 0 dagarna, förmodligen finns inte så mycket historisk data för ditt konto att en analys kan göras. Endast dagar med komplett individuell förbrukning samt förbrukningsprofil beaktas.

Testa igen om ett par dagar.

Hoppas det förklarar saken, stänger så länge, öppna igen om det inte hoppar igång snart.
