### ISSUE TITLE
Show weighted spot price also in the hour histogram

### ISSUE THREAD

**Issue by sander-visser** [dhogborg/off-peak#22]
It probably relates to the avg consumption pattern but still interresting to see how well price spikes are avoided in morning/afternoon

**Comment by dhogborg** [comment]
Interesting idea, I'll keep it in mind and add a label if someone is interested. Issue will be closed in some time but that does not mean the idea wont be implemented.

**Comment by dhogborg** [comment]
<img width="1512" alt="Screenshot 2023-01-10 at 22 28 48" src="https://user-images.githubusercontent.com/776774/211666288-7920057a-e2ec-474b-8220-ef5cb16f0580.png">

This is now implemented!
