### ISSUE TITLE
Visualization or calculation is wrong

### ISSUE THREAD

**Issue by carlosgalvezp** [dhogborg/off-peak#25]
Hi,

The app says that I'm saving -1% in the last 31 days by using timpris. However looking at the graph I can see that every single day the price I pay is always below the weighted price:

![image](https://user-images.githubusercontent.com/1083865/205492233-80f05fe2-ecca-444d-8b39-643deea126ff.png)

So if I'm always better than average, how can I be on -1%? Either the -1% is wrong, or the graph is wrong. Let me know if I can help sending some data for further troubleshooting!

**Comment by dhogborg** [comment]
Your consumption profile (grey bars) is heavily biased towards the second half of the graph where the prices are much higher (blue area). This is not unexpected as the consumption goes up when it gets cold, and this has coincided with higher prices. 

At the same time the consumption profile published by SVK has indicated less of a difference in consumption in your area between the first and second half of the time period in the graph. Had you consumed an equal amount of energy between the first and second half of the time period you would definitely be on the + side for the relative cost, but you would also had payed more in terms of actual expenditure.

**Comment by Flakmyr** [comment]
Jag kom också hit för att jag inte får ihop hur man kan ligga på minus totalt samtidigt som grafen visar att "du betalade" konstant ligger under "viktat spotpris". Jag undrar också hur månadsbrytet hanteras i 31-dagarsberäkningen. När månaden är slut blir ju månadsmedelpriset fixerat, så om man inte har med alla dagar i föregående månad så blir det konstigt att jämföra kostnaden med timavläsning och viktat spotpris.

**Comment by dhogborg** [comment]
> Jag kom också hit för att jag inte får ihop hur man kan ligga på minus totalt samtidigt som grafen visar att "du betalade" konstant ligger under "viktat spotpris". Jag undrar också hur månadsbrytet hanteras i 31-dagarsberäkningen. När månaden är slut blir ju månadsmedelpriset fixerat, så om man inte har med alla dagar i föregående månad blir det konstigt att jämföra kostnaden med timavläsning med kostnaden med viktat spotpris.

Den rullande 31-dagars beräkningen tar just nu inte hänsyn till brytdaum för månadssnittet. Det vore ju kanske en bra förbättring att göra!
