### ISSUE TITLE
Hur används viktat spotpris för beräkning av besparing

### ISSUE THREAD

**Issue by frojds** [dhogborg/off-peak#27]
Tack för en bra app!
Jag har tittat på grafer för mina båda anläggningar för perioden 1 - 15 resp 1 -14 dec. För varje dag har jag beräknat kostnaden per dag från grafen Timavläsning vs. dagsavläsning, **Konsumtion x Viktat spotpris** respektive **Konsumtion x Du betalade**.
När jag summerar och sedan jämför med sammanställningen högst upp på sidan så stämmer uppgifterna för **Konsumtion**, **Snittpris** och **Kostnad för timavräkning**. Men **Kostnaden med viktat spotpris** stämmer inte och därmed inte heller **Sparat**.
I ena anläggningen är den visade kostnaden 94 kr lägre och i den andra anläggningen är den 67 kr högre än i min beräkning.  Förbrukningen är ca 500 kWh i båda anläggningarna under perioden.  De ligger i elområde 2 resp 3.
Skulle gärna förstå vad som inte stämmer eller varför man inte kan göra beräkning på detta sätt.

**Comment by dhogborg** [comment]
Bra fråga, att dina summeringar inte stämmer är inte oväntat, en sådan summering från diagrammet går inte att göra. 

"Rörligt pris" i diagrammet visar ett pris baserat på vilka timmar det dygnet som viktades mest, och därmed vad snittpriset med rörligt avtal blev det dygnet. Men de individuella dagarna i diagrammet tar ingen hänsyn till vilka dagar som mest el användes. Priset som visas per dag är helt enkelt bara din dags-performance jämfört med ett pris viktat som ett rörligt avtal det dygnet. 

För att summera ihop till ett rörligt avtalspris för perioden tas hela periodens viktning i beaktning - om mycket el köps under en period kommer de timmarna (kanske flera dagar) viktas tyngre än timmar/dagar med mindre förbrukad el. Det ställs sedan i kontrast med din individuella förbrukning under samma tid, och skillnaden blir besparingen (eller den ökad utgiften) som visas.

**Comment by dhogborg** [comment]
Relevant kod här: https://github.com/dhogborg/off-peak/blob/master/src/lib/dataprep.ts#L203
Där räknas ett rörligt snittpris fram baserat på hela periodens förbrukningsprofil och timpriserna som hör till. Det ligger sedan till grund för total-kostnad med rörligt/viktat avtal.

**Comment by frojds** [comment]
Tack för snabbt svar. Det blev lite svårläst när du använder begreppet rörligt pris som inte används i appen. Jag hänger tyvärr inte med i ditt resonemang.
Betyder det att "Kostnad med viktat spotpris" och därmed "Sparat" som anges i längst upp i appen är korrekt mot min förbrukning (mängd och tid) för aktuell period som visas ("sedan 1:e i månaden" eller "senaste 31 dagarna)?
Däremot är det "Viktat spotpris" som anges för varje dag i diagrammet inte anpassat till min förbrukning utan på hela elområdet. 

(Om jag förstår det rätt är kostnaden baserad ett snitt för hela mitt elområde. Eftersom de flesta elbolag skapar egna snittpriser baserade på bolagets alla kunder så varierar besparingen i praktiken lite beroende på elbolag.)

**Comment by dhogborg** [comment]
Rörligt pris = viktat spotpris i dagligt tal. 

"Kostnad med viktat spotpris" ("A") är uträknat mot hela periodens förbrukningsprofil. "Sparat" är därmed differansen mellan din faktiska kostnad (med timdebiteringen) och "Kostnad med viktat spotpris".

"Viktat spotpris" ("B") (per dag) är inte anpassat till hela periodens förbrukning, utan bara det dygnet. Den prisuppgiften kan bara användas för att mäta din förbättring över de 24 timmarna jämfört med viktningen. 

Lite förenklat kan man säga att:
A: Visar hur duktig du är på att skifta din förbrukning från dyra **dagar** till billiga dagar
B: Visar hur duktig du är på att skifta din förbrukning från dyra **timmar** till billiga timmar.

Det stämmer att varje elbolag har ett eget snittpris baserat på sina kunder, men skillnaden är mycket liten i praktiken:
<img width="1161" alt="Screenshot 2022-09-18 at 10 03 51" src="https://user-images.githubusercontent.com/776774/208695000-6c87b1cc-c198-4fcd-bef2-7614328dd279.png">

**Comment by frojds** [comment]
"_"Kostnad med viktat spotpris" ("A") är uträknat mot hela periodens förbrukningsprofil._ "
Är "periodens förbrukningsprofil" anpassad till vyn som visas (sedan 1:e i månaden / senaste 31 dagarna) annars är väl en del osäkerhet i kostnad och besparing.

**Comment by dhogborg** [comment]
Ja, det är alltid den perioden som visas i graden som beräkningarna baseras på.

Jag tror detta svarar på din fråga, du får gärna ställa följdfrågor även om jag nu markerar denna issue som klar.
