### ISSUE TITLE
Unable to fetch data for ”Kostnad med viktat spotpris”

### ISSUE THREAD

**Issue by DalaDahlberg** [dhogborg/off-peak#3]
For me as a user living in a place where I have Telge Nät as owner of the net, it is not at all possible to get a value for ”Kostnad med viktat spotpris”
It never works, regardless of what browser I am using.
Here is a link to a snapshot från Offpeak.se
https://offpeak.se/snaps/gOkEZXrcjeIcwDW6ISns/graphs

**Comment by dhogborg** [comment]
Thank you! 
Seems some networks are slower at reporting the actual consumption than others. 

Best course of action should be to calculate up until the last reliable piece of data and let those networks lag behind somewhat, while still presenting meaningful data.

**Comment by dhogborg** [comment]
More snapshots that present similar or identical problems:

0tdTctP1AWVzsYw8ICHB
Sjobed00sXtNQf3PzMIt
dAx9jsOPCNYj2ne3lBBZ

**Comment by dhogborg** [comment]
@DalaDahlberg Ny release uppe i produktion, ditt snapshot fungerar till största delen, de andra snaphotsen som jag fått från användare fungerar utan problem.

Men din konsumtion som appen läser ut från tibbers API är lite udda, inga variationer mellan dagar. Hur ser din tibber app ut?

**Comment by DalaDahlberg** [comment]
Hej David.

Snyggt jobbat! Tack!

Att min data inte varierar stämmer precis med hur den detaljerade
förbrukningsgrafen ser ut i Tibber-appen. Har alltid tyckt det varit
märkligt, fattar inte varför. Vet inte ens om det är Tibber som har nåt
svaj eller Telge.
Håller på med ärende, både mot Tibber och Telge om att verkligen få igång
timavläsning, kanske är det just i att timavläsningen aldrig har funkat,
som gör att mina värden är helt jämna över månaden.

/Anders

**Comment by dhogborg** [comment]
> Hej David. Snyggt jobbat! Tack! Att min data inte varierar stämmer precis med hur den detaljerade förbrukningsgrafen ser ut i Tibber-appen. Har alltid tyckt det varit märkligt, fattar inte varför. Vet inte ens om det är Tibber som har nåt svaj eller Telge. Håller på med ärende, både mot Tibber och Telge om att verkligen få igång timavläsning, kanske är det just i att timavläsningen aldrig har funkat, som gör att mina värden är helt jämna över månaden. /Anders
> […](#)

Mycket sannolikt rapporterar din elmätare inte din förbrukning per timme. Jag hade faktiskt samma grej när jag flyttade till ett annat hus, fick min elmätare bytt av nätägaren.
