### ISSUE TITLE
Källa för viktat timpris?

### ISSUE THREAD

**Issue by Flakmyr** [dhogborg/off-peak#31]
Enligt off-peak har har jag ett snittpris på 138,2 öre ink moms per den 9e februari, vilket sägs vara 46 % sämre än viktat spotpris. Men enligt timpriskollen.se är "månadsrörligt pris just nu (SE3)" 136 öre inkl moms (exkl elcertifikat etc). Hur kommer off-peak fram till ett viktat spotpris på 95 öre för samma period?

**Comment by dhogborg** [comment]
Priset är uträknat från Svenska Kraftnäts avräkningsnotor för det nät du befinner dig i. Exakt hur kan du se i filen `dataprep.ts` och du kan själv hämta avräkningsnotor från mimer.svk.se. Den profil som används är ditt lokala nät (inte hela SE1/2/3/4) varför beräkningen kan diffa lite.

Jag tror Timpriskollen räknar utan elhandlarens avgifter för inköp, detta tar offpeak.se med då viktningen sker mot Tibbers totalpris istället för Nordpools spotpris. Eftersom avgifter för elhandel kommer faktureras ut till kund som en del av det rörliga priset är det i min mening viktigt att ta med i beräkningen. Vissa elhandelsbolag redovisar den delen av priset separat, andra inte.

För att kunna säga mer om skillnaden för just din beräkning måste jag veta lite mer, men här är ett jämförande exempel för ett hem i SE3/Göteborg under januari 2023.

**Köpt el:** 913 kWh

**Faktisk kostnad för perioden:**
Timpriskollen: 813,75 kr (beräknad)
Offpeak: 938 kr (hämtad från Tibber)

**Beräknad kostnad per kWh, viktat spotpris:**
Timpriskollen: 122 öre/kWh
Offpeak: 137 öre/kwh
Göteborg energi: 135 öre/kwh (referens, faktisk kostnad för deras kunder per kWh)

Alla priser inkl moms.

Hoppas det svarar på din fråga. Lägger in skärmdumpar på underlag nedanför.

<img width="653" alt="Screenshot 2023-02-10 at 15 23 54" src="https://user-images.githubusercontent.com/776774/218119308-2883b7c7-41e7-4680-82b9-d53858cfe895.png">
<img width="750" alt="Screenshot 2023-02-10 at 15 24 01" src="https://user-images.githubusercontent.com/776774/218119334-27d651ea-2edb-429d-8914-a330d15cfaf5.png">
<img width="706" alt="Screenshot 2023-02-10 at 15 24 48" src="https://user-images.githubusercontent.com/776774/218119349-b6135583-63e5-4811-897a-2df998f8e38b.png">

**Comment by dhogborg** [comment]
Ja, sannolikt hade din nätägare inte rapporterat in fullständiga siffror för en eller flera dagar. Om jag läst korrekt har nätägaren upp till 14 dagar på sig att justera men de allra flesta verkar vara kompletta efter 24 timmar.
