### ISSUE TITLE
Weird results since a few days back?

### ISSUE THREAD

**Issue by mvjt** [dhogborg/off-peak#35]
Greetings (from Göteborg), and thank you for a great project.

I'm normally around + 10%-15% and all of a sudden now I'm -88%. But the graph is not reflecting this either. I've tried from a new Private browser session without any improvement...Any idea? Maybe something happened with an API consumed as your source code does not seem to have any changes lately? Seems data is missing in the graph since last couple of days...

I've been using Off-Peak for a while and all of a sudden the output does not make sense. 

![image](https://github.com/dhogborg/off-peak/assets/34924009/2c5a84b0-f810-4fc1-be11-41122853c69b)

![image](https://github.com/dhogborg/off-peak/assets/34924009/d82682d7-364d-4b85-bf3d-b1e863f05ab2)

**Comment by dhogborg** [comment]
See #36 

Not sure it's the same issue, but the data source changed so hopefully that fixed it. Open the issue again if you are still seeing issues.
