### ISSUE TITLE
"Hämtningsfel, data saknas" Chrome (win, android, IOS)

### ISSUE THREAD

**Issue by larsmichelgard** [dhogborg/off-peak#36]
Får felmeddelande "Hämtningsfel, data saknas" när jag loggar in via Chrome. Det gäller i win, Android och IOS. Jag har testat med ett par olika varianter, Firefox (win) och Safari (IOS).

**Comment by d97ulf** [comment]
Samma här. Hände när jag switchade vy till "den här månaden" nu efter månadsskiftet.

**Comment by d97ulf** [comment]
Verifierade lite till i en riktig browser (brukar köra i mobilen). Hittar inga fel i loggar eller backend-requests (data ser ut att finnas i svaren).

Dock noterade jag att det är vyn "this-month" som spökar. Efter att man togglat till den så fastnar den i det läget. Man kan ta sig ur det genom att ta bort local-storage-nyckeln "period".

Dessutom visar första vyn "senaste 25 dagarna" när jag egentligen vill minnas att den borde visa "senaste 30 dagarna"?
![image](https://github.com/dhogborg/off-peak/assets/12492133/f703b63f-3502-4a02-89bd-7245621661eb)

**Comment by larsmichelgard** [comment]
@d97ulf kan du förklara hur du tar bort local-storage-nyckeln "period", för en novis? :)

**Comment by sander-visser** [comment]
> @d97ulf kan du förklara hur du tar bort local-storage-nyckeln "period", för en novis? :)

Rensa/editera dina kakor eller besök inkognito. Då funkar offpeak så.lämge du inte togglar dig fram till "denna månaden".

Jag får också senaste 24 dagarna...

**Comment by sander-visser** [comment]
Det verkar wom Mimer SVK förbrukningsprofil ej levererar nån data efter 31:e okt... Mailat SVK och påtalat...

https://mimer.svk.se/ConsumptionProfile/Submit

**Comment by d97ulf** [comment]
@larsmichelgard - som @sander-visser mycket riktigt skriver så är inkognito-mode nog enklast (CTRL+SHIFT+N i de flesta webbläsare). Annars gör du så här i Chrome:

Tryck F12 för att öppna utvecklar-mode. Välj fliken "Application", local storage för offpeak.se. Sedan kan du högerklicka på nyckeln "period" och ta bort den. Sedan kan man ladda om sidan.

![image](https://github.com/dhogborg/off-peak/assets/12492133/e35b852d-81a8-4126-ad10-9f5a0cf666b8)

**Comment by sander-visser** [comment]
@dhogborg completely empty profiles here could be allowed to consider as valid. Then some functionality would work for november...

https://github.com/dhogborg/off-peak/blob/94b9bf227a97e3170515b1a30753faf1fdfa5ee6/src/lib/dataprep.ts#L118

**Comment by sander-visser** [comment]
> Det verkar som Mimer SVK förbrukningsprofil ej levererar nån data efter 31:e okt... Mailat SVK och påtalat...
> 
> https://mimer.svk.se/ConsumptionProfile/Submit

@dhogborg jag fick svar från SVK att data nu flyttats till esett:

Då rapporteringen av förbrukningsprofil flyttats till eSett fr o m avräkningsdygnet 1 november så kommer inget att publiceras på Mimer längre. Då eSett haft problem med att ta emot värden de första dagarna har vi avvaktat med att länka vidare tills profilerna syns på eSett:s Open data.


https://opendata.esett.com/

**Comment by Allped** [comment]
provade även i Edge. precis samma fel "Hämtningsfel, data saknas"
