### ISSUE TITLE
Hur snabbt uppdateras Offpeak?

### ISSUE THREAD

**Issue by alexander** [dhogborg/off-peak#8]
Ser i Tibber att ny data har kommit in. Men Offpeak har ännu inte uppdaterats. Hur snabb är Offpeak på att uppdatera data?

**Comment by dhogborg** [comment]
Offpeak behöver data från två källor för att göra en så korrekt uträkning som möjligt, din elhandlare (tibber) och din nätleverantör (via Svenska Kraftnät). Därför är dagens siffror inte tillgängliga förrän de båda har publicerat sin data. Oftast blir svenska kraftnäts data tillgänglig mellan 08-09 på morgonen, men för vissa regioner dagen efter. Tibbers data är tillgänlig mer eller mindre direkt.
